# Generated by Django 5.1.4 on 2025-01-22 09:48

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Urban_Design', 'Urban Design'), ('GIS', 'GIS'), ('Climate_Resilience', 'Climate Resilience'), ('Geography', 'Geography')], max_length=45),
        ),
    ]
