# Generated by Django 5.1.4 on 2025-01-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
    ]
