# Generated by Django 5.1.4 on 2025-01-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_location_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sketch',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
