# Generated by Django 5.1.4 on 2025-02-12 02:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_rename_sketch_project_mini_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='map_embed',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
