# Generated by Django 5.1.4 on 2025-01-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Urban Design', 'Urban Design'), ('GIS', 'GIS'), ('Climate Resilience', 'Climate Resilience'), ('Geography', 'Geography')], max_length=50)),
                ('technologies', models.CharField(max_length=300)),
                ('map_embed', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
