# Generated by Django 5.1.4 on 2025-01-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Urban Design', 'Urban_Design'), ('GIS', 'GIS'), ('Climate Resilience', 'Climate_Resilience'), ('Geography', 'Geography')], max_length=50),
        ),
    ]
