# Generated by Django 5.1.4 on 2025-02-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
