# Generated by Django 5.1.4 on 2025-02-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sketch',
            new_name='mini_map',
        ),
    ]
